id: P5F707700
initial_creation_type: input
source_metadata:
  Title: Laghukaumudī
  Editor: James R. Ballantyne
  Publisher: Motilal Banarsidass
  Place of Publication: Delhi, India
  Year: 1976 [reprint]
  लघुकौमुदीव्याकरणम्:
    Text Version: Devanagari
    Input Personnel: Miroj Shakya
    Input Date: '2020'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Buddhist Studies
    Sponsor: University of the West
created_at: '2022-03-08T17:25:27.858383'
last_modified_at: '2022-03-08T17:25:27.858393'
